// books reducer
export const GET_BOOKS_REQUESTED = 'GET_BOOKS_REQUESTED';
export const GET_BOOKS_SUCCEEDED = 'GET_BOOKS_SUCCEEDED';
export const GET_BOOKS_FAILED = 'GET_BOOKS_FAILED';

// basket reducer
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const ORDER_BASKET_REQUESTED = 'ORDER_BASKET';
export const ORDER_BASKET_SUCCEEDED = 'ORDER_BASKET_SUCCEEDED';
export const ORDER_BASKET_FAILED = 'ORDER_BASKET_FAILED';
// user reducer
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCEEDED = 'LOGIN_USER_SUCCEEDED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCEEDED = 'REGISTER_USER_SUCCEEDED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';

// categories reducer
export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED';
export const GET_CATEGORIES_SUCCEEDED = 'GET_CATEGORIES_SUCCEEDED';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

// authors reducer
export const GET_AUTHORS_REQUESTED = 'GET_AUTHORS_REQUESTED';
export const GET_AUTHORS_SUCCEEDED = 'GET_AUTHORS_SUCCEEDED ';
export const GET_AUTHORS_FAILED = 'GET_AUTHORS_FAILED';
