// books reducer
export const GET_BOOKS_REQUESTED = 'GET_BOOKS_REQUESTED';
export const GET_BOOKS_SUCCEEDED = 'GET_BOOKS_SUCCEEDED';
export const GET_BOOKS_FAILED = 'GET_BOOKS_FAILED';

// basket reducer
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';

// user reducer
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const LOGIN_USER_SUCCEEDED = 'LOGIN_USER_SUCCEEDED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCEEDED = 'REGISTER_USER_SUCCEEDED';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
