export const API_ACTIONS = Object.freeze({
  OVERVIEW_SELL: 'OverviewSell',
  OVERVIEW_BUY: 'OverviewBuy',
  USER_INFO: 'UserInfo',
  BOOKS_SELL: 'BooksSell',
  PAGE_COUNT: 'PageCount',
  ADD_BOOK: 'AddBook',
  REGISTER_BOOK_SELL: 'RegisterBookSell',
  BOOKS_BUY: 'BooksBuy',
  REGISTER_BOOK_BUY: 'RegisterBookBuy',
  CATEGORIES: 'Categories',
  AUTHORS: 'Authors',
  PUBLISHERS: 'Publishers',
  BOOK_STATES: 'BookStates',
  BOOKS_TO_SELL: 'BooksToSell',
  BOOKS_TO_BUY: 'BooksToBuy',
  BOOKS_BUY_SEARCH: 'BooksBuySearch',
  BOOKS_SELL_SEARCH: 'BooksSellSearch',
  PHASE: 'Phase',
});
